apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-operator-apiserver
  namespace: appoperator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-operator-apiserver
rules:
  - apiGroups: ["appdefinition.abexamir.me"]
    resources: ["appdefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-operator-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-operator-apiserver
subjects:
  - kind: ServiceAccount
    name: app-operator-apiserver
    namespace: appoperator-system
