apiVersion: appdefinition.abexamir.me/v1
kind: AppDefinition
metadata:
  name: ingress-demo
  namespace: apps
spec:
  source:
    type: dockerImage
    dockerImage:
      containers:
        - name: web
          image: traefik/whoami:latest
          ports:
            - name: http
              containerPort: 80
              servicePort: 80
              protocol: TCP
              expose: true
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
          readinessProbe:
            type: httpGet
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
  replicas: 1
  serviceType: ClusterIP
  ingressClass: traefik
  domains:
    - name: whoami.demo.local
      path: /
      tls: false
      portName: http
